# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.FASTLANE_TOKEN}}
          script: |
            var msg = `👋 Thanks for participating! I will review as soon as possible, usually within a few hours.
            **Watch for notifications** as I may request some small changes to make sure this meets the guidelines.
            In a few minutes, the Netlify process at the end of this PR will make a preview available. Look for the message "Deploy preview ready!" then click the "Details" link next to it to launch a preview of your styles. Make changes if needed, and comment if you do so I can re-deploy the preview. Note that the "sponsor footer" is not available to fully style, but you may fix any issues it causes to your layout.
            Thanks again, I hope you learned something while making your stylesheet! 💫`
            var body = context.payload.pull_request.body
            if(body) {
              var incompleteGuidelines = body.includes('[]')
            }
            if(incompleteGuidelines) {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: msg
              })
            }

