# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.FASTLANE_TOKEN }}"

    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.FASTLANE_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting1!'
          })

    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.FASTLANE_TOKEN}}
        script: |
          # Create comment body as Markdown

          var msg = `👋 Thanks for participating! I will review as soon as possible, usually within a few hours.

          **Watch for notifications** as I may request some small changes to make sure this meets the guidelines.`

          # Get pull request description
          var body = context.payload.pull_request.body

