name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install Dependencies
      run: bundle install    

    - name: Run tests
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        sudo ln -s /Applications/Xcode_11.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.2.simruntime
        xcrun simctl list runtimes
        xcrun simctl list devices
        bundle exec fastlane tests

    # Artifacts allow you to persist data like test results after a job has completed, see https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts for how the artifacts works
    - name: Upload Fastlane Test results
      uses: actions/upload-artifact@v2
      with:
        name: Fastlane Test Results
        path: fastlane/test_output
