name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2.3.4

    - name: check label
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'bug') }}
      run: echo 
    
    - name: check label 2
      if: ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
      run: echo test2


    - name: Install Dependencies
      run: bundle install    

    - name: Run tests
      run: bundle exec fastlane tests

    # Artifacts allow you to persist data like test results after a job has completed, see https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts for how the artifacts works
    - name: Upload Fastlane Test results
      uses: actions/upload-artifact@v2
      with:
        name: Fastlane Test Results
        path: fastlane/test_output