name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
  pull_request: 
    branches:
      - master
      - develop
  issues:
    types: 
      - labeled

env:
  SELF_HOSTED: true

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2.3.4

    - name: check label
      if: ENV['SELF_HOSTED'] == 'true'
      run: echo $SELF_HOSTED
    
    - name: check label 2
      if: (github.event_name == 'pull_request' && (github.base_ref == 'master' || github.base_ref == 'develop') || ENV['SELF_HOSTED'] == 'false')
      run: echo $SELF_HOSTED


    - name: Install Dependencies
      run: bundle install    

    - name: Run tests
      run: bundle exec fastlane tests

    # Artifacts allow you to persist data like test results after a job has completed, see https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts for how the artifacts works
    - name: Upload Fastlane Test results
      uses: actions/upload-artifact@v2
      with:
        name: Fastlane Test Results
        path: fastlane/test_output